name: Comment Filter
description: 'GitHub Action to filter comments for suspicious content.'
branding:
  icon: "crosshair"
  color: "red"
inputs:
  exclude-contributors:
    description: 'Exclude contributors from filtering'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Remove suspicious links from issue comments
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const comment = context.payload.comment
          const { owner, repo } = context.repo

          // Extra logging for debugging
          //console.log('Repository owner:', owner)
          //console.log('Repository name:', repo)
          //console.log('Comment body:', comment.body)

          // Array of regex patterns and their replacements
          const regexReplacements = [
            // File sharing websites (general)
            {
              pattern: /(https?:\/\/)?(www\.)?(box|dropbox|mediafire|sugarsync|tresorit|hightail|opentext|sharefile|citrixsharefile|icloud|onedrive|1drv)\.com\/[^\s\)]+/gi,
              replacement: '[Link removed for safety reasons]'
            },
            // Google Drive
            {
              pattern: /(https?:\/\/)?drive\.google\.com\/[^\s\)]+/gi,
              replacement: '[Link removed for safety reasons]'
            },
            // Gofile.io
            {
              pattern: /(https?:\/\/)?(www\.)?gofile\.io\/[^\s\)]+/gi,
              replacement: '[Link removed for safety reasons]'
            },
            // Discord CDN
            {
              pattern: /(https?:\/\/)?cdn\.discordapp\.com\/[^\s\)]+/gi,
              replacement: '[Link removed for safety reasons]'
            },
            // Link shorteners
            {
              pattern: /(https?:\/\/)?(www\.)?(bit\.ly|t\.co|tinyurl\.com|goo\.gl|ow\.ly|buff\.ly|is\.gd|soo\.gd|t2mio|bl\.ink|clck\.ru|shorte\.st|cutt\.ly|v\.gd|qr\.ae|rb\.gy|rebrand\.ly|tr\.im|shorturl\.at|lnkd\.in|a4z\.in)\/[^\s\)]+/gi,
              replacement: '[Shortened link removed for safety reasons]'
            },
            // IP addresses
            {
              pattern: /https?:\/\/(\d{1,3}\.){3}\d{1,3}(:\d+)?(\/[^\s\)]*)?/gi,
              replacement: '[IP address link removed for safety reasons]'
            },
            // Multiple tagging of users
            {
              pattern: /(?:(?:^|\s|,|;)@[a-zA-Z][a-zA-Z-]*\b[^@]*){4,}/gims,
              replacement: '[Comment removed because it was tagging too many users]'
            },
          ];

          // Iterate through each regex and replace matches in the comment body
          let updatedBody = comment.body;
          regexReplacements.forEach(({ pattern, replacement }) => {
            if (pattern.test(updatedBody)) {
              console.log(`Pattern found: ${pattern}`);
              updatedBody = updatedBody.replace(pattern, replacement);
            }
          });

          // If the comment body was updated, edit the comment
          if (updatedBody === comment.body) {
            console.log('No suspicious content found.')
            return
          }

          const excludeContributors = ${{ inputs.exclude-contributors }}; 
          if (excludeContributors) {
            const contributors = await github.rest.repos.listContributors({
              owner: owner,
              repo: repo
            });
            if (contributors.data.some(contributor => contributor.login === comment.user.login)) {
              console.log('User is a contributor. Skipping comment filtering.')
              return
            }
          }

          // Extra logging for debugging  
          console.log('Updated comment body:\n', updatedBody);

          // Edit the comment with the updated body
          await github.rest.issues.updateComment({
            owner: owner,
            repo: repo,
            comment_id: comment.id,
            body: updatedBody
          });

          console.log('Comment edited successfully.');

